name: 'Emulated: prepare → test → scan'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      CONTAINER_TAG:
        description: 'CONTAINER_TAG (text)'
        required: false
        type: string

env:
  GH_REGISTRY: ghcr.io
  DH_REGISTRY: docker.io
  DHI_REGISTRY: dhi.io
  CONTAINER_TAG: initial

jobs:
  build:
    name: 'Prepare multi-platform Docker images'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    outputs:
      REPOSITORY_NAME: ${{ steps.params.outputs.REPOSITORY_NAME }}
      CONTAINER_TAG: ${{ steps.params.outputs.CONTAINER_TAG }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Get repository description'
        id: repo
        uses: stefanbosak/gh-actions/get-repo-description@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set parameters to GITHUB_ENV and GITHUB_OUTPUT'
        id: params
        shell: bash
        run: |
          CONTAINER_TAG="${{ env.CONTAINER_TAG }}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.CONTAINER_TAG }}" != "" ]]; then
              CONTAINER_TAG="${{ github.event.inputs.CONTAINER_TAG }}"
            fi
          fi
          REPOSITORY_NAME="$(echo '${{ github.repository }}' | cut -d'/' -f2)"
          REPOSITORY_DESCRIPTION="${{ steps.repo.outputs.description }}"
          TIMESTAMP="$(git log -1 --format=%cI)"
          echo "CONTAINER_TAG=${CONTAINER_TAG}" >> ${GITHUB_ENV}
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> ${GITHUB_ENV}
          echo "REPOSITORY_DESCRIPTION=${REPOSITORY_DESCRIPTION}" >> ${GITHUB_ENV}
          echo "TIMESTAMP=${TIMESTAMP}" >> ${GITHUB_ENV}
          echo "GITHUB_ENV:"
          cat ${GITHUB_ENV}
          echo "CONTAINER_TAG=${CONTAINER_TAG}" >> ${GITHUB_OUTPUT}
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> ${GITHUB_OUTPUT}
          echo "REPOSITORY_DESCRIPTION=${REPOSITORY_DESCRIPTION}" >> ${GITHUB_OUTPUT}
          echo "GITHUB_OUTPUT:"
          cat ${GITHUB_OUTPUT}

      - name: 'Cleanup ${{ env.GH_REGISTRY }} registry'
        uses: actions/delete-package-versions@main
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ env.REPOSITORY_NAME }}
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 2

      - name: 'Cleanup ${{ env.DH_REGISTRY }} registry'
        uses: stefanbosak/gh-actions/cleanup-dockerhub-old-digests@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.run_id }}
          ref-name: ${{ github.ref_name }}
          dh-user: ${{ secrets.DH_USER }}
          dh-token: ${{ secrets.DH_TOKEN }}
          repository-name: ${{ env.REPOSITORY_NAME }}

      - name: 'Set up QEMU (arm64)'
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/arm64

      - name: 'Set up Docker buildx'
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: 'Login to ${{ env.GH_REGISTRY }} registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: false
          logout: true

      - name: 'Login to ${{ env.DH_REGISTRY }} registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          ecr: false
          logout: true

      - name: 'Login to ${{ env.DHI_REGISTRY }} registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.DHI_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          ecr: false
          logout: true

      - name: 'Build, push'
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          no-cache: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ env.GH_REGISTRY }}/${{ github.repository }}:${{ env.CONTAINER_TAG }}
            ${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}
          labels: |
            org.opencontainers.image.created=${{ env.TIMESTAMP }}
            org.opencontainers.image.description=${{ needs.prepare.outputs.REPOSITORY_DESCRIPTION }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=image,compression=gzip,compression-level=3,force-compression=true

      - name: 'Extract all stored digests'
        shell: bash
        run: |
          JSON=$(docker buildx imagetools inspect ${{ env.GH_REGISTRY }}/${{ github.repository }}:${{ env.CONTAINER_TAG }} --format '{{json .}}')

          ALL_DIGESTS=$(echo "${JSON}" | jq -r '
            [
              .manifest.digest,

              (
                .manifest.manifests[]
                | select(.mediaType == "application/vnd.docker.distribution.manifest.v2+json")
                | .digest
              )
            ]
            | join(" ")
          ')

          echo "${ALL_DIGESTS}" > /tmp/digests-all.txt

      - name: 'Upload extracted digests as artifact'
        uses: actions/upload-artifact@main
        with:
          name: digests-all
          path: /tmp/digests-all.txt
          if-no-files-found: error
          retention-days: 7

  test:
    name: 'Test image (${{ matrix.platform_pair }})'
    needs: build
    if: success()
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            platform_pair: linux-amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform_pair: linux-arm64
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Run tests in Docker container'
        shell: bash
        run: |
          docker run --rm \
            -v /dev:/dev \
            -u root \
            ${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ needs.build.outputs.REPOSITORY_NAME }}:${{ needs.build.outputs.CONTAINER_TAG }} \
            sh -c 'v=$(gemini --version | grep -oP "\d+\.\d+\.\d+(-\d+)?"); echo "GEMINI_CLI_VERSION=${v}";'

  scan:
    name: 'Scan image (${{ matrix.platform_pair }})'
    needs: [build]
    if: success()
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            platform_pair: linux-amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform_pair: linux-arm64
    permissions:
      contents: read
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Run Trivy scan'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ needs.build.outputs.REPOSITORY_NAME }}:${{ needs.build.outputs.CONTAINER_TAG }}'
          format: 'json'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'
          version: 'latest'
          output: scan-report-${{ matrix.runner }}.json

      - name: 'Store scan report as artifact'
        uses: actions/upload-artifact@main
        with:
          name: scan-report-${{ matrix.runner }}
          path: scan-report-${{ matrix.runner }}.json
          retention-days: 7
          overwrite: true
          compression-level: 0
